Episode:
    type: entity
    table: episodes
    repositoryClass: EpisodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        number:
            type: integer
        season:
            type: integer
        tvdbId:
            type: integer
        firstAired:
            type: datetime
            nullable: true
        thumbnail:
            type: string
            length: 50
            nullable: true
        downloaded:
            type: boolean
    manyToOne:
        tvshow:
            targetEntity: TVShow
            joinColumn:
                name: tv_show_id
                referencedColumnName: id
            nullable: false
            inversedBy: episodes
    lifecycleCallbacks: {  }
